//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.30 at 12:16:40 PM EET 
//


package lt.ztadas.xmlclasses;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public GetWordsSortedRequest createGetWordsSortedRequest() {
        return new GetWordsSortedRequest();
    }

    public GetWordsSortedResponse createGetWordsSortedResponse() {
        return new GetWordsSortedResponse();
    }

}
