//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.30 at 12:16:40 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ztadas.lt/xmlschema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lt.ztadas.xmlclasses;
